[2024-05-01T18:51:53.374+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T18:51:53.398+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.read_and_clean_csv manual__2024-05-01T18:51:51.133447+00:00 [queued]>
[2024-05-01T18:51:53.409+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.read_and_clean_csv manual__2024-05-01T18:51:51.133447+00:00 [queued]>
[2024-05-01T18:51:53.410+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-01T18:51:53.427+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): read_and_clean_csv> on 2024-05-01 18:51:51.133447+00:00
[2024-05-01T18:51:53.435+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1099) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T18:51:53.437+0000] {standard_task_runner.py:63} INFO - Started process 1101 to run task
[2024-05-01T18:51:53.437+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'read_and_clean_csv', 'manual__2024-05-01T18:51:51.133447+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp2xf6ri6b']
[2024-05-01T18:51:53.438+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask read_and_clean_csv
[2024-05-01T18:51:53.489+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.read_and_clean_csv manual__2024-05-01T18:51:51.133447+00:00 [running]> on host a747c391e266
[2024-05-01T18:51:53.589+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='read_and_clean_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T18:51:51.133447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T18:51:51.133447+00:00'
[2024-05-01T18:51:53.590+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T18:51:53.615+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-01T18:51:53.837+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-01T18:51:53.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T18:51:53.849+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=read_and_clean_csv, execution_date=20240501T185151, start_date=20240501T185153, end_date=20240501T185153
[2024-05-01T18:51:53.892+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T18:51:53.915+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-01T18:51:53.918+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
